### ISSUE TITLE
New HiRISE images to process for upload

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planet-four#162]
We're preparing for the next set of images we'd like to put on the site. @astopy we'd want uploaded and cut into tiles:

ESP_029548_0945
ESP_030106_0950
ESP_029473_0950
ESP_030251_0950
ESP_029328_0950

The scripts Chris Snyder wrote should be somewhere in this repo. The code that parses the images into subjects should work as. I think the HiRISE website has changed a bit so the code that grabs the metadata from it might need some modifications. We'll likely need these images by sometime by mid September, but I wanted to give plenty of warning.

**Comment by astopy** [comment]
I've updated the scripts and run them against those images. They're ready to activate now if that's OK? Though it looks like it's only produced about 500 new subjects from them, so do you want me to do some more?

**Comment by mschwamb** [comment]
@astopy thanks. Is there metadata captured for these objects for Talk?  I think @parrish has to do something to make that live on Talk. I'll ask the team if we have another target region to include.

**Comment by mschwamb** [comment]
@astopy the team wants to add these images as well:

ESP_030619_0945
ESP_029907_0945
ESP_029696_0945
ESP_029551_0945
ESP_029340_0945
ESP_028997_0945
ESP_028852_0945

**Comment by astopy** [comment]
That brings us up to 2107 subjects.

I'm not sure about your talk question... the metadata in ouroboros should all be the same, but if something extra needs to happen in talk I'll need to leave that for @parrish

**Comment by parrish** [comment]
Oh boy.  Yeah, I can scrape it if you get me the manifest.

Yay xpath selectors...

**Comment by astopy** [comment]
Cool. The manifest is on EC2, there's an instance called "Data processing" and the manifest is at `/data/planetfour/manifest.json`. I haven't ingested that into Ouroboros yet, though.

@mschwamb Shall we just make those live, or did you want to add any more images?

**Comment by mschwamb** [comment]
Thanks @parrish and @astopy. Yeah at this point once the Talk data is ready then we can make them live.

**Comment by parrish** [comment]
Actually, it looks like all the metadata is in the manifest already.  Unless I'm missing something?

**Comment by mschwamb** [comment]
Sorry miswording on my part, I guess I meant putting the stuff from the manifest on Talk,

**Comment by parrish** [comment]
I'm still confused.  There aren't any additional steps to add the data to talk.

Back in the first version of talk, we had to add them separately.  Maybe that's what you're thinking of?

**Comment by mschwamb** [comment]
Hmm.. every other upload on Planet Four, there always something you had to do in Talk, maybe that got sorted at some point and I've forgotten.  Sorry. My recollection could definitely be wrong. Can you send me a subject id for a new subject, and I'll double check.

**Comment by parrish** [comment]
Nothing has been created recently, I assume Adam was waiting to start it.

**Comment by astopy** [comment]
OK, I've gone ahead and created the new subjects. Here's an example:

https://api.zooniverse.org/projects/planet_four/subjects/APF0002a3v/
