### ISSUE TITLE
Unpausing these subjects and making them live

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planet-four#164]
@astopy when you get a second, can you please turn on the subjects associated with these these HiRISE image ids (should be name in the database)? Thanks. 

PSP_002081_1055
PSP_002147_1055
PSP_002226_1055
PSP_002292_1055
PSP_002437_1055
PSP_002582_1055
PSP_003070_1055
PSP_003215_1055
PSP_002567_0955
PSP_002936_0955
PSP_003068_0955
PSP_003213_0955
PSP_003424_0955
PSP_003824_0845
PSP_003912_0955
PSP_004202_0955
PSP_004941_0955
PSP_005046_0955
PSP_003345_0955
PSP_003982_0845

**Comment by astopy** [comment]
These should be active now.

**Comment by mschwamb** [comment]
Thanks @astopy
