### ISSUE TITLE
add in new redirect for new P4 project

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planet-four#165]
@astopy I think this is in your purview. Can you create a redirect for me for the new P4 project under development.

have http://ridges.planetfour.org redirect to https://www.zooniverse.org/projects/mschwamb/planet-four-ridges

**Comment by astopy** [comment]
@mschwamb There's an issue stopping me deploying this at the moment, but it should hopefully be live later today.

**Comment by astopy** [comment]
@mschwamb This is live now.

**Comment by mschwamb** [comment]
Many Thanks @astopy
