### ISSUE TITLE
adding in a link to Planet Four: Ridges to P4 landing page for January 17

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planet-four#167]
@astropy I think this in your purview - In prep for launch of the new P4 project, we'd like to have a link on the P4 landing page to it. 
 
Get rid of 'Follow the project on social media to stay updated on our status and how we are using your efforts to produce science.' and have a P4: Ridges mention there instead:

'Help map polygonal ridges in Arabia Terra on Mars with our new project
Planet Four: Ridges '

hyperlink should be to http://ridges.planetfour.org

Also in the P4: Terrains line  'Help map the exotic terrains of Mars' south pole with our new project' change 'new' to 'companion'

This would be for an expected launch on January 17th. We're beta testing at the end of the week.

**Comment by astopy** [comment]
@mschwamb The code for this is ready to go. Just let me know when you're ready for us to deploy it.

**Comment by mschwamb** [comment]
Thanks. If it fits can we keep the social media icons (but with not text just the icons) after the new stuff you added.

**Comment by astopy** [comment]
@mschwamb Sure. I've updated it to put the icons back in.

**Comment by mschwamb** [comment]
Thanks. We're good to go and make this live. Planet Four: Ridges is  ready to accept classifications, so  whenever you get in if you want make it live works for me. @mrniaboc has to set the sit to launch approved and he's sending the newsletter out at 3-4 GMT if you want to coordinate with him.

**Comment by mschwamb** [comment]
forgot to tag you @astopy  (see above)

**Comment by astopy** [comment]
@mschwamb @mrniaboc  This is deployed now

**Comment by mschwamb** [comment]
Thanks
