### ISSUE TITLE
unpausing P4 data 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planet-four#170]
@astopy  we're out of data on Planet Four. Would you be willing to unpause these subjects if they aren't retired. Thanks 

PSP_002558_0955
PSP_003231_0950
PSP_003921_0850
PSP_004088_0950
PSP_002399_1025
PSP_002544_1025
PSP_002900_1025
PSP_003322_1025
PSP_003345_0955
PSP_003982_0845
PSP_002822_0955
PSP_003468_0955
PSP_003798_0955
PSP_003864_0955
PSP_003758_0950
PSP_003222_0845

**Comment by astopy** [comment]
Sure, those are active now.

**Comment by mschwamb** [comment]
Thanks
