### ISSUE TITLE
Processing new Planet Four images for upload

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planet-four#171]
Hi @astopy, 
When you get a chance would you be able to process these HiRISE images listed below  with the Zooniverse scripts? Given these fans are so big we wanted to get this region done with the current P4 before we switch over to panoptes since the size of the subject image is much much smaller in panoptes compared to the current P4 interface. . Hoping to switch over to panoptes next year.  We fully understand that this might take weeks or months for you to get to.
Thanks, 

ESP_040216_0950
ESP_040189_0950
ESP_039359_0950
ESP_038462_0950
ESP_038040_0950
ESP_037842_0950
ESP_029548_0945
ESP_049209_0950
ESP_048576_0950
ESP_048431_0950
ESP_047653_0950
ESP_047363_0950
ESP_046862_0950
ESP_046770_0950
ESP_046769_0950

**Comment by astopy** [comment]
These should be live now
