### ISSUE TITLE
Results page

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/planet-four#174]
Hello!
We have submitted our first paper and now need a results page at www.planetfour.org/results
similar to https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/results.
Because I want to put the paper on arXiv, if possible, I'd like this to go live soon, so that the paper is available for proposal reviewers, pretty please? ;)
Thanks in advance!

**Comment by mschwamb** [comment]
@astopy I can help with this text for this if needed. Thanks

**Comment by mschwamb** [comment]
Given we're gong to need this in month or two @michaelaye can you add the specific links for the files that Adam will need to add or share the directory in dropbox with him? For each file can you write a few sentence description. You can refer back to the paper, paper tables, etc

**Comment by mschwamb** [comment]
@adammcmaster we'll need this next. I've asked @michaelaye to send you the data files and also our pdf explanations from the paper text of what are in these files
