### ISSUE TITLE
Move authors page from beta to non-beta link

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planet-four#177]
@adammcmaster can you please move https://www.planetfour.org/beta/#/authors  to https://www.planetfour.org/authors  - it's okay if this is live before the paper is accepted. We should be resubmitting to the journal hopefully in the next week or two.

**Comment by mschwamb** [comment]
@adammcmaster When me move over to panoptes, I imagine the structure will change again so that '#' might not be needed. Is that correct? If  so it might be better to have the redirect anyway. Can you set that up?

**Comment by adammcmaster** [comment]
The redirect is live now. There are a few ways to handle the existing site once the project moves to Panoptes -- I don't think we've thought about which option will be best for this project yet.

**Comment by mschwamb** [comment]
Thanks @adammcmaster
