### ISSUE TITLE
results page needs to serve and link raw data

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/planet-four#178]
We forgot to add links to the raw data and intermediate pipeline outputs (for partial re-analysis).
I need to zip that all up and make sure to anonymize the user names.
Will post the data links here when I got the stuff ready.
We suggest to add 2 more sections at the end of the current results page: 
* Planet Four Raw Data (Mars Years 29 and 30)
* Intermediate pipeline results

I also will update the linked PDF that describes the structure. It's all written in the Appendix of the just resubmitted paper, but I need to paste more into this cut-out pdf.

Hope that's not too much effort on your side, Adam? Incidentally, in panoptes, are we able to edit result pages on our own, including uploading datasets? That would be cool and we wouldn't need to spend valuable developers' time on it.

**Comment by mschwamb** [comment]
@michaelaye are you ready with the files so @adammcmaster can post this - the paper was accepted a day or so again

**Comment by michaelaye** [comment]
Here's the link to the raw data file with the user-names replaced to provide anonymity:

https://www.dropbox.com/s/cpplfg3qf0inpsf/P4_catalog_v1.0_raw_classifications.hdf?dl=1

I'll provide the PDF file with added info next.

**Comment by michaelaye** [comment]
First, here are the intermediate pipeline products for applying different cuts to the catalog:

https://www.dropbox.com/s/vg7aznyt0broguv/P4_catalog_v1.0_pipeline_products.zip?dl=1

**Comment by michaelaye** [comment]
And here's the full Appendix of the paper that describes all the files that we provide:

https://www.dropbox.com/s/im9xxxong5rc0dz/P4_paper1_Appendix.pdf?dl=1

**Comment by adammcmaster** [comment]
Thanks, I can add these. Could you just clarify how you want that to look on the page? 

Are these to be added to the existing numbered list after the tile catalog? Or as a whole new section below Data Release 1?

Is the new appendix PDF supposed to replace the existing one which has just appendix E?

Could you provide the full text descriptions you want to go alongside each of these?

**Comment by adammcmaster** [comment]
Thanks, I can add these. Could you just clarify how you want that to look on the page? 

Are these to be added to the existing numbered list after the tile catalog? Or as a whole new section below Data Release 1?

Is the new appendix PDF supposed to replace the existing one which has just appendix E?

Could you provide the full text descriptions you want to go alongside each of these?

**Comment by mschwamb** [comment]
@michaelaye can you please generate a pdf that only includes appendix C -E. Having the additional bits of text are going to confuse someone who just wants to download the files

**Comment by mschwamb** [comment]
@adammcmaster yes, you can add them at the top of the existed number listed - thanks

**Comment by adammcmaster** [comment]
I'm off now for two weeks, so I'll leave this to someone else to update the page while I'm away. cc @camallen @srallen @rogerhutchings

**Comment by michaelaye** [comment]
Here's the link to the reduced appendix:

https://www.dropbox.com/s/6pavhqvh8oliuyf/P4_data_files_appendix.pdf?dl=0

This new appendix pdf replaces the previous one, yes, and is a cut-and-paste from the paper appendix sections C to E.

Full text descriptions for the linked files:

Raw data: 

"Planet Four raw classification data that was used in our reduction pipeline to create the fan and blotch catalog that is linked on this page (described in Appendix C of the paper, linked below). User names have been anonymized for data privacy."

Intermediate data products:

"These are the products as described  in Appendix D of the paper, linked below). A researcher can apply a different cut on the probability of fan vs blotch identification using these products, reproducing a new fan catalog."

The link to the appendix file would need updating as well, from the current:

"More details about the structure of these files can be found in Appendix E"
to
"More details about the structure of these files can be found in Appendices C to E"

Thanks!

**Comment by rogerhutchings** [comment]
Apologies, my mistake. That's been removed.

**Comment by michaelaye** [comment]
Ok, looks good to me! Thanks!
