### ISSUE TITLE
updated catalog files for results page

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/planet-four#180]
Hi!
We found some issues during proofing at the journal with our catalogs, where we did not clean-up a special kind of duplicates properly.
This has been cleaned up now, and we created a v1.1 of all result catalog files, that should be replaced on planetfour.org/results.
The recent "Raw data" and "Intermediate data products" have not been changed.

Here's a link to the zip file with all other files:

https://www.dropbox.com/s/9hb7sw5a5zxt45z/P4_catalog_v1.1.zip?dl=1

Thanks!

**Comment by mschwamb** [comment]
@adammcmaster any chance you could get to this today. I'm giving a talk so there's a chance people might download the files. I get this is a last minute request so if you can't get to this today I fully understand.
