### ISSUE TITLE
New images for upload

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/planet-four#183]
Hi @adammcmaster  as per the email conversation with Chris please parse these images for  subject creation upload on Planet Four. I'll let you know which image's classifications we want to make live for classification

ESP_046681_0935
ESP_046642_0935
ESP_046971_0935
ESP_047696_0935
ESP_047459_0935
ESP_047103_0935
ESP_047961_0935
ESP_047327_0935

**Comment by adammcmaster** [comment]
Sure, I'll take a look at this next week.

**Comment by mschwamb** [comment]
@adammcmaster checking in. Anything you need for me. The priority is to make the subjects from ESP_046971  active first.

**Comment by adammcmaster** [comment]
I'm planning to process these today. I'll make ESP_046971 live as soon as it's ready in that case.

**Comment by adammcmaster** [comment]
I ran into a couple of issues with the data import scripts because of some things that changed since the last time we ran them, so it's going to be tomorrow at the earliest before this is ready now.

**Comment by adammcmaster** [comment]
The new subjects are ready, and I've activated ESP_046971_0935 and paused the rest so they're ready to be activated when needed.
