### ISSUE TITLE
Moving marks create artifacts in Firefox

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/planet-four#88]
Can anyone off chance think of what might be causing the behavior shown below?

https://www.dropbox.com/s/dhsltumbs82rgab/Screenshot%202014-03-30%2017.30.31.png

https://www.dropbox.com/s/fu5t46mvokdpkzt/Screenshot%202014-03-27%2016.39.42.png

User on Win7/latest Firefox. Repeatable behavior. Could not duplicate on my Win7 machine.

**Comment by mschwamb** [comment]
This may be helpful in tracking the bug down. Most detailed description yet from a volunteer:

Hi - same problem pops up every couple of days for me too - I've tried on Chrome, Firefox, IE and even Safari - sometimes it works fine of one, but not the others. Sometimes it has the same problem over all 4 browsers. Other days 3 out of four don't work - each time it's a different browser that is ok (yesterday IE was fine, day before it was Chrome). Very strange. Today, it is not working in Chrome, Firefox or IE - but it is fine in Safari! Always seems to be the same section of the images - right hand side and bottom - about a 2cm strip across the bottom and slightly thinner section up the right. Markers leave multiple trails and you can't adjust them if their expander points are inside the "problem area". I have still been placing the markers (adjusting their direction and shape first, then carefully dragging them into place - hoping that it is in the correct location!!)

**Comment by mschwamb** [comment]
Someone got what looks like a console grab during the time their  browser was drawing the artifacts and there java errors listed but not sure if it's related. You can see the screen grabs [here](http://talk.planetfour.org/#/boards/BPF0000004/discussions/DPF0000gj7?page=5&comment_id=55658252b6021d457b000694) on Talk.

**Comment by chrissnyder** [comment]
I think those are different errors. I cleaned up the language selection problems a bit ago. Shouldn't have any others problems on that front.

Still not sure what causes the weird artifacts while classifying though.
